/* ==== 功能：论文研读 START ==== */
const Papers = {
  editingId:null,
  items(){return Store.list('papers',(a,b)=>(b.date||'').localeCompare(a.date||''));},
  render(){const dateEl=document.getElementById('paperDate');if(dateEl&&!dateEl.value)dateEl.value=Util.today();const list=this.items(),box=document.getElementById('paperList');box.innerHTML=list.length?list.map(x=>x.id===this.editingId?`<div class="item"><div class="grow"><div class="field-grid two"><input id="paperInlineTitle" value="${Util.esc(x.title)}" aria-label="论文题目"><select id="paperInlineStatus">${['待读','在读','读完'].map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></div><input id="paperInlineDate" type="date" value="${Util.esc(x.date||Util.today())}"><textarea id="paperInlineNote">${Util.esc(x.note||'')}</textarea><div class="row"><button class="btn" onclick="Papers.saveEdit()">保存修改</button><button class="btn ghost" onclick="Papers.cancelEdit()">取消</button></div></div></div>`:`<div class="item"><div class="grow"><b>${Util.esc(x.title)}</b> <span class="pill">${Util.esc(x.status)}</span><div class="item-meta">${Util.esc(x.date)}</div>${x.note?`<div class="note">${Util.esc(x.note)}</div>`:''}</div><button class="btn ghost" onclick="Papers.edit('${x.id}')">编辑</button><button class="del" onclick="Papers.cycle('${x.id}')">状态</button><button class="del" onclick="Papers.del('${x.id}')">✕</button></div>`).join(''):'<div class="empty">待读队列还是空的</div>';},
  add(){const title=document.getElementById('paperTitle').value.trim(),note=document.getElementById('paperNote').value.trim(),status=document.getElementById('paperStatus').value,date=document.getElementById('paperDate').value||Util.today();if(!title)return UI.toast('先填写论文题目');if(date>Util.today())return UI.toast('不能记录未来的研读');Store.upsert('papers',{title,note,status,date});['paperTitle','paperNote'].forEach(id=>document.getElementById(id).value='');this.render();UI.toast(date===Util.today()?'已加入阅读队列':`已补记 ${date} 的研读`);},
  edit(id){if(this.items().some(x=>x.id===id)){this.editingId=id;this.render();}},
  cancelEdit(){this.editingId=null;this.render();},
  saveEdit(){const x=this.items().find(v=>v.id===this.editingId),title=document.getElementById('paperInlineTitle').value.trim(),note=document.getElementById('paperInlineNote').value.trim(),status=document.getElementById('paperInlineStatus').value,date=document.getElementById('paperInlineDate').value||x.date;if(!x||!title)return UI.toast('论文题目不能为空');if(date>Util.today())return UI.toast('不能记录未来的研读');Store.upsert('papers',Object.assign({},x,{title,note,status,date}));this.editingId=null;this.render();UI.toast('研读记录已更新');},
  cycle(id){const x=this.items().find(v=>v.id===id);if(!x)return;const seq=['待读','在读','读完'];Store.upsert('papers',Object.assign({},x,{status:seq[(seq.indexOf(x.status)+1)%3]}));this.render();},
  del(id){if(confirm('从阅读队列删除？')){Store.softDelete('papers',id);this.render();}}
};
/* ==== 功能：论文研读 END ==== */
